# Generated by Django 3.1.2 on 2020-10-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_entry_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'entries'},
        ),
    ]
