# Generated by Django 3.1.2 on 2020-10-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_auto_20201011_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='read_num',
            field=models.IntegerField(default=0),
        ),
    ]
