# Generated by Django 3.1.2 on 2020-10-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_entry_read_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='read_num',
        ),
        migrations.CreateModel(
            name='ReadNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField(default=0)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.entry')),
            ],
        ),
    ]
