# Generated by Django 3.1.2 on 2020-10-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_auto_20201012_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='published_date',
        ),
        migrations.AddField(
            model_name='entry',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
