# Generated by Django 3.1.2 on 2020-10-12 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_auto_20201012_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_added',
        ),
    ]
