# Generated by Django 3.1.2 on 2020-10-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0018_auto_20201012_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_date'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
