# Generated by Django 3.1.2 on 2020-10-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0019_auto_20201012_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
