# Generated by Django 3.1.2 on 2020-10-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0020_auto_20201012_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
